const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{Scene1: 0},
	{Scene2: 0},
	{Player: 0},
	{Scene3: 0},
	{Scene4: 0},
	{currentSceneNumber: 0},
	{lastDirection: 0},
	{NPC1: 0},
	{Keyboard: 0},
	{NPC2: 0},
	{FireCivilianNPC: 0},
	{Mission1: 0},
	{Mission2: 0},
	{Mission3: 0},
	{Mission3_2: 0},
	{DialogueText: 0},
	{FireEngineerNPC: 0},
	{NPC4: 0},
	{Forum: 0},
	{CutsceneSprite: 0},
	{TiledBackground: 0},
	{Text: 0},
	{Text2: 0},
	{TiledBackground2: 0},
	{WaterBucket: 0},
	{DropZoneMarker: 0},
	{TutorialText: 0},
	{Text4: 0},
	{IcedScene1: 0},
	{useless: 0},
	{MainSceneText: 0},
	{Text6: 0},
	{ACUnit: 0},
	{Sprite2: 0},
	{MissionNPC1: 0},
	{LoadingScreen: 0},
	{ScienceItem: 0},
	{MissionNPC2: 0},
	{Text5: 0},
	{Text7: 0},
	{ZZEndText: 0},
	{ZZStartText: 0},
	{Scene5: 0},
	{IceBook: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{StatueBox1: 0},
	{StatueBox2: 0},
	{Statue1: 0},
	{Statue2: 0},
	{EnterSign: 0},
	{UniversityBox: 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{TiledBackground9: 0},
	{TiledBackground10: 0},
	{TiledBackground11: 0},
	{TiledBackground12: 0},
	{TiledBackground13: 0},
	{TiledBackground14: 0},
	{TiledBackground15: 0},
	{TiledBackground16: 0},
	{Text10: 0},
	{Sprite3: 0},
	{CourtBox: 0},
	{TiledBackground17: 0},
	{TiledBackground18: 0},
	{TiledBackground19: 0},
	{TiledBackground20: 0},
	{TiledBackground21: 0},
	{Sprite4: 0},
	{Text11: 0},
	{TiledBackground22: 0},
	{MayorCar: 0},
	{NPC3: 0},
	{MissionNPC3: 0},
	{Fountain: 0},
	{Fire1: 0},
	{Fire2: 0},
	{Text12: 0},
	{TiledBackground23: 0},
	{MissionNPC4: 0},
	{Engine: 0},
	{EngineBox: 0},
	{TimerText: 0},
	{Sans: 0},
	{Mission5Library: 0},
	{NPC5: 0},
	{MissionNPC5: 0},
	{IceCourt: 0},
	{Text13: 0},
	{IceCity: 0},
	{Text14: 0},
	{EndScene: 0},
	{Greenhouse: 0},
	{GardenBox: 0},
	{TiledBackground24: 0},
	{TiledBackground25: 0},
	{LabBox: 0},
	{TiledBackground26: 0},
	{TiledBackground27: 0},
	{TiledBackground28: 0},
	{TiledBackground29: 0},
	{Text15: 0},
	{TiledBackground30: 0},
	{FactoryBox: 0},
	{TiledBackground31: 0},
	{TiledBackground32: 0},
	{TiledBackground33: 0},
	{TiledBackground34: 0},
	{TiledBackground35: 0},
	{Text16: 0},
	{Spray: 0},
	{Puddle: 0},
	{FireDrop: 0},
	{Lighter: 0},
	{DialogueBox: 0},
	{MissionTextBox: 0},
	{MissionText: 0},
	{InstructionBox: 0},
	{InstructionText: 0},
	{TiledBackground36: 0},
	{TiledBackground37: 0},
	{CreditsBox: 0},
	{CreditsText: 0},
	{Text8: 0},
	{Remote: 0},
	{LabRobot: 0},
	{TiledBackground38: 0},
	{MayorAir: 0},
	{Sprite: 0},
	{MayorPlane: 0},
	{TiledBackground39: 0},
	{TiledBackground40: 0},
	{TiledBackground41: 0},
	{TiledBackground42: 0},
	{MoneyBag: 0},
	{TargetNPC1: 0},
	{TargetNPC2: 0},
	{NPC7: 0},
	{NPC6: 0},
	{MissionNPC7: 0},
	{MissionNPC6: 0},
	{TiledBackground43: 0},
	{TrueEnd: 0},
	{ForumBox: 0},
	{StatueBox: 0},
	{Mission6Card: 0},
	{Mission9Card: 0},
	{Mission10Card: 0},
	{Mission11Card: 0},
	{TrueEndBox: 0},
	{TrueEndDialogue: 0},
	{Audio: 0}
];

self.InstanceType = {
	Scene1: class extends self.ITiledBackgroundInstance {},
	Scene2: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Scene3: class extends self.ITiledBackgroundInstance {},
	Scene4: class extends self.ITiledBackgroundInstance {},
	NPC1: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	NPC2: class extends self.ISpriteInstance {},
	FireCivilianNPC: class extends self.ISpriteInstance {},
	Mission1: class extends self.ITiledBackgroundInstance {},
	Mission2: class extends self.ITiledBackgroundInstance {},
	Mission3: class extends self.ITiledBackgroundInstance {},
	Mission3_2: class extends self.ITiledBackgroundInstance {},
	DialogueText: class extends self.ITextInstance {},
	FireEngineerNPC: class extends self.ISpriteInstance {},
	NPC4: class extends self.ISpriteInstance {},
	Forum: class extends self.ISpriteInstance {},
	CutsceneSprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	WaterBucket: class extends self.ISpriteInstance {},
	DropZoneMarker: class extends self.ISpriteInstance {},
	TutorialText: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	IcedScene1: class extends self.ITiledBackgroundInstance {},
	useless: class extends self.ITiledBackgroundInstance {},
	MainSceneText: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	ACUnit: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	MissionNPC1: class extends self.ISpriteInstance {},
	LoadingScreen: class extends self.ISpriteInstance {},
	ScienceItem: class extends self.ISpriteInstance {},
	MissionNPC2: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	ZZEndText: class extends self.ITextInstance {},
	ZZStartText: class extends self.ITextInstance {},
	Scene5: class extends self.ITiledBackgroundInstance {},
	IceBook: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	StatueBox1: class extends self.ISpriteInstance {},
	StatueBox2: class extends self.ISpriteInstance {},
	Statue1: class extends self.ISpriteInstance {},
	Statue2: class extends self.ISpriteInstance {},
	EnterSign: class extends self.ISpriteInstance {},
	UniversityBox: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	TiledBackground16: class extends self.ITiledBackgroundInstance {},
	Text10: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	CourtBox: class extends self.ISpriteInstance {},
	TiledBackground17: class extends self.ITiledBackgroundInstance {},
	TiledBackground18: class extends self.ITiledBackgroundInstance {},
	TiledBackground19: class extends self.ITiledBackgroundInstance {},
	TiledBackground20: class extends self.ITiledBackgroundInstance {},
	TiledBackground21: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text11: class extends self.ITextInstance {},
	TiledBackground22: class extends self.ITiledBackgroundInstance {},
	MayorCar: class extends self.ISpriteInstance {},
	NPC3: class extends self.ISpriteInstance {},
	MissionNPC3: class extends self.ISpriteInstance {},
	Fountain: class extends self.ISpriteInstance {},
	Fire1: class extends self.ISpriteInstance {},
	Fire2: class extends self.ISpriteInstance {},
	Text12: class extends self.ITextInstance {},
	TiledBackground23: class extends self.ITiledBackgroundInstance {},
	MissionNPC4: class extends self.ISpriteInstance {},
	Engine: class extends self.ISpriteInstance {},
	EngineBox: class extends self.ISpriteInstance {},
	TimerText: class extends self.ITextInstance {},
	Sans: class extends self.ISpriteInstance {},
	Mission5Library: class extends self.ISpriteInstance {},
	NPC5: class extends self.ISpriteInstance {},
	MissionNPC5: class extends self.ISpriteInstance {},
	IceCourt: class extends self.ITiledBackgroundInstance {},
	Text13: class extends self.ITextInstance {},
	IceCity: class extends self.ITiledBackgroundInstance {},
	Text14: class extends self.ITextInstance {},
	EndScene: class extends self.ISpriteInstance {},
	Greenhouse: class extends self.ISpriteInstance {},
	GardenBox: class extends self.ISpriteInstance {},
	TiledBackground24: class extends self.ITiledBackgroundInstance {},
	TiledBackground25: class extends self.ITiledBackgroundInstance {},
	LabBox: class extends self.ISpriteInstance {},
	TiledBackground26: class extends self.ITiledBackgroundInstance {},
	TiledBackground27: class extends self.ITiledBackgroundInstance {},
	TiledBackground28: class extends self.ITiledBackgroundInstance {},
	TiledBackground29: class extends self.ITiledBackgroundInstance {},
	Text15: class extends self.ITextInstance {},
	TiledBackground30: class extends self.ITiledBackgroundInstance {},
	FactoryBox: class extends self.ISpriteInstance {},
	TiledBackground31: class extends self.ITiledBackgroundInstance {},
	TiledBackground32: class extends self.ITiledBackgroundInstance {},
	TiledBackground33: class extends self.ITiledBackgroundInstance {},
	TiledBackground34: class extends self.ITiledBackgroundInstance {},
	TiledBackground35: class extends self.ITiledBackgroundInstance {},
	Text16: class extends self.ITextInstance {},
	Spray: class extends self.ISpriteInstance {},
	Puddle: class extends self.ISpriteInstance {},
	FireDrop: class extends self.ISpriteInstance {},
	Lighter: class extends self.ISpriteInstance {},
	DialogueBox: class extends self.ISpriteInstance {},
	MissionTextBox: class extends self.ISpriteInstance {},
	MissionText: class extends self.ITextInstance {},
	InstructionBox: class extends self.ISpriteInstance {},
	InstructionText: class extends self.ITextInstance {},
	TiledBackground36: class extends self.ITiledBackgroundInstance {},
	TiledBackground37: class extends self.ITiledBackgroundInstance {},
	CreditsBox: class extends self.ISpriteInstance {},
	CreditsText: class extends self.ITextInstance {},
	Text8: class extends self.ITextInstance {},
	Remote: class extends self.ISpriteInstance {},
	LabRobot: class extends self.ISpriteInstance {},
	TiledBackground38: class extends self.ITiledBackgroundInstance {},
	MayorAir: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	MayorPlane: class extends self.ISpriteInstance {},
	TiledBackground39: class extends self.ITiledBackgroundInstance {},
	TiledBackground40: class extends self.ITiledBackgroundInstance {},
	TiledBackground41: class extends self.ITiledBackgroundInstance {},
	TiledBackground42: class extends self.ITiledBackgroundInstance {},
	MoneyBag: class extends self.ISpriteInstance {},
	TargetNPC1: class extends self.ISpriteInstance {},
	TargetNPC2: class extends self.ISpriteInstance {},
	NPC7: class extends self.ISpriteInstance {},
	NPC6: class extends self.ISpriteInstance {},
	MissionNPC7: class extends self.ISpriteInstance {},
	MissionNPC6: class extends self.ISpriteInstance {},
	TiledBackground43: class extends self.ITiledBackgroundInstance {},
	TrueEnd: class extends self.ISpriteInstance {},
	ForumBox: class extends self.ISpriteInstance {},
	StatueBox: class extends self.ISpriteInstance {},
	Mission6Card: class extends self.ISpriteInstance {},
	Mission9Card: class extends self.ISpriteInstance {},
	Mission10Card: class extends self.ISpriteInstance {},
	Mission11Card: class extends self.ISpriteInstance {},
	TrueEndBox: class extends self.ISpriteInstance {},
	TrueEndDialogue: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {}
}