const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.wrap,
		C3.Plugins.Text,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.PickRandom
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{player: 0},
	{DestroyOutsideLayout: 0},
	{Bullet: 0},
	{Keyboard: 0},
	{Wrap: 0},
	{Enemy: 0},
	{Sprite: 0},
	{TiledBackground2: 0},
	{Text2: 0},
	{Text: 0},
	{EnemyBullet: 0},
	{Text3: 0},
	{xPos: 0},
	{AlienDirection: 0},
	{AlienY: 0},
	{Score: 0},
	{killed: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	player: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Text2: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {}
}